dbt-labs/dbt-redshift

.github/scripts/integration-test-matrix.js, .github/workflows/integration.yml, dev_requirements.txt, tests/unit/test_context.py
Partial resolution of dbt-labs/dbt#3924. If we agree with the approach here, we can extend to `dbt-snowflake` + `dbt-bigquery`.
- Run the `integration` workflow nightly at 5 UTC, to identify any regressions caused by changes in `dbt-core`.
- Install `dbt-core` from `HEAD` (instead of hardcoding `develop` branch) to get latest changes
- Remove logic from `integration` workflow that picks plugins to test based on file changes. This is nice for PRs that only edit the README, but it's not as important now that this repo only contains the Redshift plugin. This logic seemed to be running into bugginess on `push` triggers ([e.g.](https://github.com/dbt-labs/dbt-redshift/runs/3777004562)); we'll be able to see after merging this PR.
=> Update integration workflow

tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one.sql, tests/integration/incremental_schema_tests/models/incremental_append_new_columns_remove_one_target.sql, tests/integration/incremental_schema_tests/models/schema.yml, tests/integration/incremental_schema_tests/test_incremental_schema.py, tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one.sql, tests/integration/incremental_schema_tests/tests/select_from_incremental_append_new_columns_remove_one_target.sql
resolves https://github.com/dbt-labs/dbt-core/issues/4144
Following https://github.com/dbt-labs/dbt-core/pull/4170, it makes sense to add a dedicated tests to avoid regression on that change for Redshift integration.
I didn't edited the changelog as it only affects the tests.
=> Add tests on incremental materialization

.github/workflows/integration.yml
When a scheduled run fails, this will post it to slack
=> Slack message for failed nightly runs

setup.py
=> Fix package version

.bumpversion.cfg, setup.py
resolves #50 
This fixes the issue with the package naming bug we saw when we released and there was no `rc` or `b` appended to the end. Instead this just relies on versionBump to get the package version
=> Fixing version bump bug

.github/workflows/stale.yml
resolves # 
No issue created yet
Adding Stale issue/PR message github action workflow to all adapters
=> adding stale github action workflow to all adapter repos

.bumpversion.cfg, CHANGELOG.md, setup.py
preping for release
backporting #52
=> Backporting : Fixing version bump bug (#52)

CHANGELOG.md, dev_requirements.txt, pytest.ini, tests/conftest.py, tests/functional/adapter/test_basic.py, tox.ini
resolves #78 
Use the new testing framework in Redshift.
=> Initial code to use dbt.tests.adapter in Redshift

.bumpversion.cfg, .github/workflows/main.yml, dbt/adapters/redshift/__version__.py, setup.py, tests/integration/docs_generate_tests/test_docs_generate.py, tests/unit/test_context.py
- Bump `main` to `1.2.0a1`
- Skip the `test-build` step while in alpha, since we don't expect this to work (no PyPI distribution for `dbt-core==1.2.0a1`)
=> Bump to 1.2.0a1. Skip `test-build` step during alpha

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml, dev_requirements.txt, setup.py, tests/integration/base.py, tox.ini
We should add Python 3.10 to our test runs. I had to upgrade some dependencies to make it work. I'm guessing those older versions weren't 3.10 compatible. I also added the suppression of logbook warnings like we did in dbt-core
=> Updating to test py 3.9 and 3.10

.github/workflows/integration.yml
Environment variables don't appear to be loading in https://github.com/dbt-labs/dbt-redshift/pull/131 for some reason. This PR is a low-risk experiment to add the relevant GitHub Actions config to the default branch in the hopes that it will load these environment variables when running CI going forward.
=> Grantee env vars for GitHub Actions

tests/integration/defer_state_test/test_defer_state.py
Any chance this does it? :)
Longer term:
- convert this test
- we probably don't even need it in `dbt-redshift`
=> Rename compiled_sql to compiled_code

.github/workflows/backport.yml, .github/workflows/version-bump.yml
related to #151 
Updates version bump to also generate changelog, uses centralized reusable workflow that all adapters (and eventually core) can also use.
Adds backport action now that changie is implemented.
=> version bump, changie and backports

.changes/unreleased/Under the Hood-20220812-151707.yaml, tests/test_incremental_run_result.py
resolves #5351 (dbt-core). Test shorter columns are not considered a schema change for incremental materialization when `on_schema_change = sync_all_columns`
=> add test for column precision change

dbt/include/redshift/macros/adapters.sql, tests/functional/adapter/relation_name_tests/test_relation_name.py
Removing unneeded code. Sister PR in dbt core.
=> Remove unneeded code.

.changes/unreleased/Under the Hood-20220824-102919.yaml, tests/conftest.py, tests/integration/base.py
resolves #142 
Configure more connection retries for CI tests since upstream adapter has exponential backoff
=> Configure more connection retries for CI tests

.changes/unreleased/Under the Hood-20220913-143919.yaml, dbt/adapters/redshift/__init__.py, dbt/adapters/redshift/connections.py, dbt/adapters/redshift/impl.py
resolves #185
Thanks to [this change](https://github.com/dbt-labs/dbt-core/commit/e95e36d63b8fb479078d7cc4eed2e3e8f3b37f43) we are now properly inheriting typing from dbt-core resulting in mypy discovering new conflicts. Ignoring these for now and creating a new issue to investigate further at later date.
=> ignore adapter MyPy issues

.changes/unreleased/Features-20220919-235003.yaml, tests/functional/adapter/utils/test_data_types.py
resolves #189
redshift component of https://github.com/dbt-labs/dbt-core/issues/5739
=> add type boolean

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #https://github.com/dbt-labs/dbt-core/issues/6203
Upgrade actions/setup-python from v2 to v4.3.0 to bring in all the updates for deprecations
Defines Python Version to use when installing dependencies
=> [CT-1469] init pr for short term python version issue fix

.pre-commit-config.yaml
resolves: [Flake8 took down the gitlab repository in favor of github](https://www.reddit.com/r/Python/comments/yvfww8/flake8_took_down_the_gitlab_repository_in_favor/)
Updating to [documented](https://flake8.pycqa.org/en/latest/user/using-hooks.html#usage-with-the-pre-commit-git-hooks-framework) github flake8 repo: https://github.com/pycqa/flake8.
=> Redshift Implementation of flake8 fix to swap gitlab for github

dbt/adapters/redshift/connections.py, tests/unit/test_redshift_adapter.py
> Do we set the Redshift session timeout_sec to 14400?  I have a customer that is seeing a large number of connections (336) during a 4 thread job run, and I am wondering if we are not reusing connections and a bunch are just idle and not timing out early enough.. Thoughts?
We supplied fields on the scale of seconds. It should instead be minutes.
=> Change keepalives idle field to numbers appropriate for minutes, not seconds.

.github/workflows/release.yml
Updated release workflow trigger to be able to be manually run.
=> fix trigger

.github/workflows/release.yml
I previously pinned to the shorthand SHA but the full sha is required.
=> Pin full commit sha

.changie.yaml
resolves #237 
Additional testing showed that Issue is an int which does not allow multiple issue to be listed via CLI.  This updates the type to be string.  Also fixes list generation of issues/PRs for contributor footer.
=> update changie type to be string to allow multiple issues

.changie.yaml, .github/workflows/bot-changelog.yml
Backport #280 
Necessary to allow other back ports to work without conflicts. Since PR is no longer required on main, when a change is back ported it will not have the PR in the changelog yaml and will break changelog generation.
=> [BACKPORT] Remove PR requirement from Changelog (#280)

.changes/unreleased/Under the Hood-20230223-110314.yaml, dbt/include/redshift/macros/adapters.sql
resolves #330
Rename "constraints_enabled" to "contract"
=> Rename "constraints_enabled" to "contract"

.changes/unreleased/Fixes-20230316-132120.yaml, dbt/adapters/redshift/connections.py, dbt/adapters/redshift/impl.py, dbt/include/redshift/macros/relations.sql, tests/functional/adapter/backup_tests/models.py, tests/functional/adapter/backup_tests/test_backup_table.py, tests/functional/adapter/test_basic.py
resolves #365
- Update `RedshiftAdapter` to include link_cache_relation methods that were inadvertently dropped when migrating from inheriting from `PostgresAdapter` to inheriting directly from `SQLAdapter`
- Add test case to catch this error in the future
=> ADAP-366: View Rerun Bug

.changes/1.5.0/Features-20221209-105640.yaml, dbt/adapters/redshift/impl.py, dev-requirements.txt
resolves #342 
Uses centralized warnings from `dbt-core` for constraints.
=> update to generalize constraints

.github/workflows/nightly-release.yml
The test workflow needs to point to 1.4.latest until 1.5.0 final is released.
=> revert changes to point to 1.4.latest until 1.5.final is released

.changes/unreleased/Dependencies-20230421-032407.yaml, dev-requirements.txt
Upgrade `pytest` to `~=7.3` to align with other adapters and dependabot.
=> Update pytest requirement from ~=7.2 to ~=7.3

.changes/unreleased/Fixes-20230428-142321.yaml, dbt/adapters/redshift/connections.py, tests/unit/test_redshift_adapter.py
resolves #419 
Added region as a field and remove the host parsing hard-coding
=> Fix for #419: dbt-redshift 1.5 does not work with non-standard redshift hostnames

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #417 
Update versions of used Github Actions ahead of:
[node12 deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (Summer 2023)
[set-output deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) (fully disabled on 31st May 2023)
=> update used gh actions ahead of set-output, node12 deprecation

.changes/unreleased/Fixes-20230509-143721.yaml, dbt/adapters/redshift/connections.py, tests/unit/test_redshift_adapter.py
fixes the signature change in `execute` from `dbt-core` here: https://github.com/dbt-labs/dbt-core/pull/7545
=> Fix execute signature based on core

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #417 
Backport to `1.3.latest`.  Does not require a patch release since this is only around testing automation.
=> [Backport] 1.3.latest gh deprecations

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #417 
Backport to `1.4.latest`.  Does not require a patch release since this is only around testing automation.
=> [Backport] 1.4.latest gh deprecations

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #417 
Backport to `1.5.latest`.  Does not require a patch release since this is only around testing automation.
=> [Backport] 1.5.latest gh deprecations

.changes/unreleased/Fixes-20230520-043039.yaml, dbt/adapters/redshift/connections.py, tests/functional/adapter/test_autocommit.py
resolves #463 
An imperfect but what I think is a necessary solution to unblock users from #425 
Root cause: Connection objects used in Python must have [`autocommit = True`](https://docs.aws.amazon.com/redshift/latest/mgmt/python-connect-examples.html) to run `CREATE DATABASE`, `VACUUM`, etc..
But, this is a Python-level thing we need to alter. The docs I linked above have this snippet.
Yep, this is official guidance. So, we have to alter the connection in the Python post hoc instead of altering the connection instantiation function.
All together -- if we make it an opt-in config for users, we could direct them to define a separate target with `autocommit=True`. This isn't great but it was straightforward enough for me to get 1.5 users unblocked within the sprint!
Let users configure …
=> Add autocommit feature to let dbt users run certain db commands in macros

.changes/unreleased/Fixes-20230508-094834.yaml, dbt/adapters/redshift/connections.py, tests/unit/test_redshift_adapter.py
resolves #433 backport to 1.5.latest
changes connect_timeout default to None optional which is same as redshift_connector
noticed some small changes in main and wanted to make sure this older work also doesn't needed to be backported: https://github.com/dbt-labs/dbt-redshift/commit/52a666eaf1592e6bf87a01501a1fa444c1cd2a52
=> [Backport] 433

.changes/unreleased/Fixes-20230524-151825.yaml, dbt/include/redshift/macros/adapters.sql, dev-requirements.txt
resolves #441
I suspect there's a bug that affects `redshift_connector` (and possibly `pg8000` too) where a [comment](https://docs.aws.amazon.com/redshift/latest/dg/r_COMMENT.html) like the following raises an error regardless if using `paramstyle = 'pyformat'` or `paramstyle = 'format'`:
```sql
comment on table customers is '95% of customer records';
```
To solve, I took the implementation of `postgres_escape_comment` from https://github.com/dbt-labs/dbt-core/pull/2378 and tweaked it slightly in order to escape all `%` symbols to be `%%` instead.
Added text containing `%` to the functional tests within dbt-core so that we can cover this test case in dbt-redshift and other adapters.
=> Escape `%` symbols in table/view/column comments

.changes/unreleased/Fixes-20230524-165236.yaml, dbt/include/redshift/macros/materializations/seeds/helpers.sql
mitigates (but does not solve root cause of) #347
For seed CSV files above a certain size, the `redshift_connector` raises the following error:
```
'h' format requires -32768 <= number <= 32767`
```
To mitigate the effect on downstream users, we can lower the default batch size from `10000` to `500`.
In local performance testing using 1.4 (and `psychopg2`), a CSV with 6,000 rows took ~10 seconds to load batch sizes of `10000` to `500` (no difference).
Using 1.5 and (and `redshift_connector`), it took ~13 seconds using a batch size of `500` and ~23 seconds using a batch size of `50`.
My suggestion would be to use a batch size of `500` to mitigate the effect on downstream users while still pursuing a more satisfactory solution (which will probably require a change in `redshift_connector`). …
=> Use smaller batch size for seeds

.changes/unreleased/Breaking Changes-20230530-165542.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/main.yml, .github/workflows/nightly-release.yml, CONTRIBUTING.md, dev-requirements.txt, setup.py, tox.ini
resolves dbt-labs/dbt-core#7082
Drop support for py37.
=> drop support for py37

.changes/unreleased/Breaking Changes-20230522-111945.yaml, .changes/unreleased/Fixes-20230512-082027.yaml, dbt/adapters/redshift/connections.py, tests/unit/test_redshift_adapter.py
resolves #429
Translate from the user provided `sslmode` to the parameters required by the redshift connector in order to preserve the `dbt-redshift` config interface after the shift from `psycopg2` to `redshift-connector`.
Please see this PR for a significantly more detailed writeup: https://github.com/dbt-labs/dbt-redshift/pull/439. Thanks @jiezhen-chen for this work and the detail in the write-up. Most of the changes with my name attached revolve around reworking @jiezhen-chen's solution to align with pre-existing patterns in `dbt-core`.
=> ADAP-512: sslmode translation

.github/workflows/integration.yml, .github/workflows/main.yml
resolves #417 
Backport to `1.0.latest`.  Does not require a patch release since this is only around testing automation.
=> [Backport] 1.0.latest gh deprecations

dbt/include/redshift/macros/adapters.sql
This reverts commit adb44828fefff91dd6e97ee20ee8fb7e395a2ece.
After the release of `redshift_connector` [2.0.911](https://pypi.org/project/redshift-connector/2.0.911/), we don't need (or want) https://github.com/dbt-labs/dbt-redshift/pull/466 anymore. If it is left in, then extra % characters will be introduced within comments.
- Nope - ~I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-redshift/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)~
=> Revert "Escape `%` symbols in table/view/column comments (#466)"

.changes/unreleased/Fixes-20230628-123227.yaml, tests/unit/utils.py
resolves https://github.com/dbt-labs/dbt-core/pull/7955
=> Remove dependent_projects argument from PartialProject call in unit tests

.changes/unreleased/Breaking Changes-20230530-165542.yaml, .github/scripts/integration-test-matrix.js, .github/workflows/main.yml, .github/workflows/nightly-release.yml, CONTRIBUTING.MD, setup.py, tox.ini
Dropping support for py37 backport (#474)
=> [Backport 1.2.latest] Dropping support for py37

.changes/unreleased/Fixes-20230706-001056.yaml, setup.py
resolves #518
Exclude `dbt-redshift==2.0.912` due to a regression in the patch release.
=> exclude redshift-connector==2.0.912

.changes/unreleased/Fixes-20230706-001056.yaml, .changes/unreleased/Fixes-20230706-012233.yaml, setup.py, tests/unit/test_context.py
`defer_relation` is an optional argument that was added to `ModelNode` as part of the `dbt clone` work. Despite it being optional, `MagicMock` was trying to mock it up, which failed validation tests on `Path`. This new argument was added to the mock parameters with a value of `None` to avoid creating it.
=> Add new `defer_relation` argument to `mock_model`

.github/pull_request_template.md
resolves #  
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#  
change in pull request templet added extra whitespace.
=> fix whitespace change

.changes/unreleased/Fixes-20230713-105351.yaml, setup.py
=> hard pin to latest compatible version

.changes/unreleased/Fixes-20230713-190412.yaml, dbt/adapters/redshift/connections.py
resolves #536 
No [docs updates](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) needed.
[this gist](https://gist.github.com/dataders/5dfdc66a80031733ea8582c2a1976cfa/revisions/?diff=split) shows that `sql = self._add_query_comment(sql)` was removed as part of #251. and never added back. this omission was not picked up due to faulty tests that were surfaced in https://github.com/dbt-labs/dbt-core/issues/7845 and fixed in https://github.com/dbt-labs/dbt-core/pull/7928.
Add it back 😎
Vive les commentaires de requête !
=> add query commenting back

.changes/unreleased/Under the Hood-20230724-164439.yaml, .github/workflows/stale.yml
The stale workflow uses an old version
Update the stale workflow to use the centralized version.
=> Update stale workflow to use the centralized version

.changes/unreleased/Under the Hood-20230808-141645.yaml, tests/functional/adapter/materialized_view_tests/test_materialized_views.py, tests/functional/adapter/materialized_view_tests/utils.py
=> ADAP-761: [backport] Add retry logic to flaky MV tests to avoid "cannot open relation with OID" error

tox.ini
We were missing env vars in tox for data dog.
Add them to tox.ini
=> ADAP-796: Add datadog env vars to tox.ini

.changes/unreleased/Fixes-20230830-164611.yaml, dbt/adapters/redshift/connections.py
resolves #592
dbt-core removed hologram as a dependency. FieldEncoder was being imported from hologram.
Remove FieldEncoder and its registered encoder, since it doesn't appear to be used.
=> Remove import of FieldEncoder from hologram

.changes/unreleased/Fixes-20230908-113019.yaml, tests/functional/adapter/expected_stats.py
resolves #597 
change to agate_helper in core requires an update to the data type expected value in the test.
This pr is dbt-redshift versions of earlier work we did but had to revert in dbt-bigquery see: https://github.com/dbt-labs/dbt-bigquery/pull/890 and https://github.com/dbt-labs/dbt-bigquery/pull/894
merge into main and backport to 1.6.latest when core does
=> [ADAP-878] update expected values

.changes/unreleased/Fixes-20230912-133327.yaml, dbt/include/redshift/macros/relations/materialized_view/alter.sql, tests/functional/adapter/materialized_view_tests/utils.py
use get_replace_sql in redshift__get_alter_materialized_view_as_sql
resolves #
=> Fix replace sql macro

.changes/unreleased/Under the Hood-20230914-135547.yaml, dbt/adapters/redshift/relation_configs/materialized_view.py, dbt/adapters/redshift/utility.py, tests/functional/adapter/materialized_view_tests/test_materialized_views.py, tests/unit/relation_configs/test_materialized_view.py
=> allow for bool/str input to backup/autorefresh when configuring materialized views

.changes/unreleased/Fixes-20230923-091155.yaml, dbt/include/redshift/macros/relations.sql
- Move relation name `not equals` from outer SELECT `where` clause to dependency CTE 
- Seems to more reliably push query planner to avoid a nested loop 
- Should preserve original intent, i.e. to exclude self-references from final result 
- Execution plan suggests this reduces the row estimate for the outer SELECT 
- Real-world testing on internal company cluster under conditions where nested loop is used for original, shows that the new approach continues to perform and behave as expected (no nested loop)
resolves #609
> copied from issue *Current Behavior*
When running the statement in [relations.sql](https://github.com/dbt-labs/dbt-redshift/blob/538ad793769269454ff390135566a85d729fcdcc/dbt/include/redshift/macros/relations.sql), our Redshift cluster query planner will, seemingly at …
=> Avoid nested loop in query planner execution

tests/functional/adapter/utils/test_utils.py
resolves https://github.com/dbt-labs/dbt-core/issues/8172
In https://github.com/dbt-labs/dbt-core/issues/8172 we moved the `date_spine` macro and sub macros from dbt-utils to dbt-core. As such we should begin testing these macros to ensure they work properly on this adapter.
Begin running the tests for the `date_spine` macro and sub macros
=> Add tests for `date_spine` macro, and sub macros

.changes/unreleased/Under the Hood-20230925-150132.yaml, dev-requirements.txt, tests/functional/adapter/dbt_show/test_dbt_show.py
resolves https://github.com/dbt-labs/dbt-redshift/issues/616
=> add dbt show tests

.changes/unreleased/Fixes-20231025-203732.yaml, dbt/adapters/redshift/relation_configs/materialized_view.py, tests/functional/adapter/materialized_view_tests/test_materialized_views.py
Backport b4176b95ee976b6c503a49904f754c8953730480 from #643.
=> [Backport 1.6.latest] Fix parsing of database results for materialized view autorefresh

.changes/unreleased/Features-20231030-101055.yaml, dbt/adapters/redshift/impl.py
This change follows a similar pattern to [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L53) to allow an adapter to configure it's dependencies' logging, this has the added benefit of not having the debug logs for redshift-connector turned on by default during testing.
=> allow user to set debug level via env var

.changes/unreleased/Fixes-20231030-234315.yaml, dbt/include/redshift/macros/catalog.sql, tests/functional/adapter/catalog_tests/files.py, tests/functional/adapter/catalog_tests/test_relation_types.py
resolves #652, dbt-labs/dbt-core#8864
Materialized views show up as views in catalog queries.
- write a test demonstrating the issue
- update the catalog query to correctly assign type for materialized views
=> ADAP-973: Fix issue where materialized views were being mapped as views in catalog queries

.changes/unreleased/Fixes-20231026-164623.yaml, dbt/include/redshift/macros/relations/materialized_view/describe.sql
resolves #641
When doing a dbt run on a redshift serverless cluster, permission denied errors will happen when dbt attempts to query the svt_mv_info table. This is due to that table not being queryable by any user in redshift serverless [as described here](https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-monitoring.html#serverless_views-monitoring).
This can be remedied by a custom macro for redshift__describe_materialized_view, which references the svv_mv_info view instead of the svt_mv_info table as shown below
=> Fixes #641 by using the svv_mv_info view which is queryable

.changes/unreleased/Dependencies-20231130-044332.yaml, setup.py, tests/functional/adapter/test_basic.py, tests/unit/test_redshift_adapter.py
resolves #624
The `boto3` dependency is as of writing, pegged 7 major versions behind the latest `boto3` release.
The only context where `boto3` is referenced within the `dbt-redshift` repository is within a unit test which raises the question on whether the `boto3` version peg is even necessary since it is already a transitive dependency of `redshift-connector`.
At the current time, this version peg frustrates compatibility of `dbt-redshift` with the latest `awscli`, `boto3` and `botocore` versions as well as other unrelated dbt plugins.
Remove `boto3` as a direct dependency for `dbt-redshift`
=> Fix #624 by removing unnecessary boto3 version peg

.changes/unreleased/Fixes-20231026-164623.yaml, dbt/include/redshift/macros/relations/materialized_view/describe.sql
Backport 058a3ffa2aff4b556d495667912ce50028da9cd0 from #647.
=> [Backport 1.7.latest] Fixes #641 by using the svv_mv_info view which is queryable

.changes/unreleased/Dependencies-20240118-095740.yaml, setup.py
=> upgrade 1.7.latest redshift driver constraint to allow for `<=2.0.918, >=2.0.913`

.changes/unreleased/Dependencies-20240124-111727.yaml, dbt/adapters/redshift/connections.py, dbt/adapters/redshift/impl.py, dbt/adapters/redshift/relation.py, dbt/adapters/redshift/relation_configs/dist.py, dbt/adapters/redshift/relation_configs/materialized_view.py, dbt/adapters/redshift/relation_configs/sort.py, dev-requirements.txt, setup.py, tests/functional/adapter/incremental/test_incremental_strategies.py, tests/functional/adapter/test_query_comment.py, tests/unit/test_redshift_adapter.py, tests/unit/utils.py
- migrate to common/adapters
resolves #
=> Migrate to dbt-adapters and dbt-common

.changes/unreleased/Fixes-20240206-132326.yaml, dbt/adapters/redshift/connections.py
resolves #710
We are seeing an error when running `dbt docs generate` on a set of sources that uses external tables. This error is similar to what we saw here: https://github.com/dbt-labs/dbt-core/issues/8217.
We need to initialize `Lexer` in `sqlparse` prior to using `sqlparse`, as is done in this PR: https://github.com/dbt-labs/dbt-core/pull/8215
=> [Bug] Initialize sqlparse lexer prior to using sqlparse

.changes/unreleased/Features-20231219-120533.yaml, dbt/adapters/redshift/impl.py, dbt/include/redshift/macros/metadata/relation_last_modified.sql, tests/functional/adapter/sources_freshness_tests/files.py, tests/functional/adapter/sources_freshness_tests/test_get_relation_last_modified.py
Backport d77f5ee9561bf11eae56b2832340e3c11005b6f9 from #694.
=> [Backport 1.7.latest] Implementation of metadata-based freshness

.changes/unreleased/Features-20240318-030018.yaml, .github/workflows/release-internal.yml, dbt/adapters/redshift/__version__.py, setup.py
resolves #38 in epic
We need a workflow to release things internally
Write the workflow. I'll be opening up a PR for the workflow this one calls.
Followup actions including reconfiguring secrets and doing a full run start to finish!
=> Add Redshift internal build process workflow

.changes/unreleased/Fixes-20240317-113447.yaml, setup.py
resolves #730
A bug causing an SSL error was introduced to `redshift-connector` in `2.0.918`.
We need to pin `redshift-connector` to `<2.0.917` to resolve the issue for now. We will need to determine a long term solution, which may be as simple as skipping `2.0.918`, as we did with `2.0.914`, after `redshift-connector` resolves the underlying issue.
This will need to be backported to `1.7.latest`, where it was introduced.
=> [Bug] Python driver 2.0.918 causes SSL error. Need to revert back to 2.0.917

.changes/unreleased/Under the Hood-20240227-002713.yaml, dbt/adapters/redshift/relation.py, dbt/include/redshift/macros/relations/materialized_view/create.sql, dbt/include/redshift/macros/relations/view/rename.sql, dbt/include/redshift/macros/relations/view/replace.sql, tests/unit/test_renamed_relations.py
Backport c99c73bd0386e2641c825b8e36c5bc0229cd3258 from #723.
=> [Backport 1.7.latest] Fix the renamed relations code

.changes/unreleased/Dependencies-20240403-134607.yaml, setup.py, tests/functional/adapter/test_query_comment.py
We need to preserve backwards compatibility for installing this package.
Include `dbt-core` as a dependency for installation, but do not depend on it within functional code.
=> Add `dbt-core~=1.8.0a1` as convenience dep

.changes/unreleased/Dependencies-20240416-195919.yaml, .changes/unreleased/Security-20240416-195919.yaml, setup.py
resolves #
we pinned sqlparse to not go out of range of dbt-core and they recently upgraded we are raising pin to stay in line
similar issue seen in `dbt-postgres` when migrating tests from that repo back to adapters/core https://github.com/dbt-labs/dbt-core/pull/9951
=> update sqlparse to be in line with dbt-core 

.pre-commit-config.yaml
See https://github.com/dbt-labs/dbt-adapters/issues/144
=> Add pre-commit check for dbt-core

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.1.latest] Pin `macos` runners to `macos-12` (#787)

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.2.latest] Pin `macos` runners to `macos-12` (#787)

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.3.latest] Pin `macos` runners to `macos-12` (#787)

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.6.latest] Pin `macos` runners to `macos-12` (#787)

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.7.latest] Pin `macos` runners to `macos-12` (#787)

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.4.latest] Pin `macos` runners to `macos-12` (#787)

.github/scripts/integration-test-matrix.js, .github/workflows/main.yml
=> [Backport 1.5.latest] Pin `macos` runners to `macos-12` (#787)

.github/workflows/integration.yml
We're not referencing the macos runner correctly (`macos12` instead of `macos-12`).
Fix it.
=> Fix macos runner typo

.github/workflows/release-internal.yml
Some of the integration tests require the AWS CLI.
- vendor the internal PyPI release pipeline
- simplify the pipeline to the scope of `dbt-redshift` (e.g. remove conditionals checking for `hatch`, skipping certain tests, etc.)
- insert the step to configure the aws cli client
- break out between flaky and non-flaky tests, and align with existing integration test workflow in general
=> Add aws cli setup to the internal PyPI release pipeline

.github/workflows/integration.yml
=> [Backport 1.7.latest] Fix macos runner typo (#820)

.changes/unreleased/Fixes-20240612-131752.yaml, setup.py
We want to fold in the fix from [this patched issue on redshift connector](https://github.com/aws/amazon-redshift-python-driver/issues/204).
Up the pin. soft pinned since either patch version in `2.1` should work
=> Pin to 2.1.1 and below to fix the cursor error.

.github/workflows/docs-issues.yml
https://github.com/dbt-labs/adapters-team-private/issues/143
We are wanting to make sure all adapters have a docs-issue workflow and if it exists currently make sure it is in same state as dbt-core workflow to where we trigger off issues now. for parity.
=> update user docs-issue workflow 

.github/workflows/release-internal.yml
=> Update internal release naming and arguments

setup.py
We calculate the `dbt-postgres` version dependency based on the version of `dbt-redshift`. This causes issues when we want to keep `dbt-postgres` at a different version than `dbt-redshift`.
Treat `dbt-postgres` like any other dependency and simply hard code the pin.
=> remove calculated version for dbt-postgres dependency

.changes/unreleased/Fixes-20240625-170324.yaml, dev-requirements.txt, tests/functional/adapter/unit_testing/fixtures.py, tests/functional/adapter/unit_testing/test_unit_testing.py
resolves #821 
Depends on upstream: https://github.com/dbt-labs/dbt-core/pull/10366
Redshift chooses to default a Null value's type in-field to be `VARCHAR(1)`. There's also no clean way without changing the unit test fixture interface for users to supply the type to an empty 
Sort rows such that we find a row with no Null values. 
If a row with no Null values does not exist, throw a parser error since we cannot guarantee type of that column.
This also handles when a single column has all null values, which would also throw this error.
This solution was picked for expediency, low blast radius of problem, and rarity of use case. The alternate would be some complicate type determination logic in core by picking a non null value and sending that to the database to discover what type the …
=> Adap 821/unit test infer wrong datatype

tests/integration/column_quoting/test_column_quotes.py
The test `tests/integration/column_quoting/test_column_quotes.py::TestColumnQuotingDefault::test_redshift_column_quotes` is consistently failing. While this version is no longer supported, this would block merging anything, such as a security vulnerability patch.
Skip the test.
=> Skip failing test `TestColumnQuotingDefault` on unsupported versions

.changes/unreleased/Under the Hood-20240719-133151.yaml, dev-requirements.txt
We list `freezegun` as a test dependency, but it's not used anywhere. It just winds up generating `dependabot` PRs.
Remove the dependency. It was left over from the monorepo but does not apply here.
=> Remove `freezegun` as a test dependency since it is not used

.changes/unreleased/Fixes-20240625-170324.yaml, dbt/include/redshift/macros/adapters/unit_testing.sql, dev-requirements.txt, tests/functional/adapter/unit_testing/fixtures.py, tests/functional/adapter/unit_testing/test_unit_testing.py
resolves #821 
Note this Pr depends on the [base adapter PR here](https://github.com/dbt-labs/dbt-adapters/pull/270).
Take 2 in response to #860 
Redshift provides a macro that will check for the bad row scenario and throw a more helpful error to the user than the existing type mismatch bug that caused this error in the first place.
=> Adap 821/unit tests infer wrong datatype for None values in fixtures

dev-requirements.txt
```
syntax error at or near "'foreign_key_model'" in context "key references ref('foreign_key_model'", at line 9, column 52
compiled Code at target/run/test/models/my_model.sql
```
This is related to a similar snowflake issue https://github.com/dbt-labs/dbt-snowflake/pull/1150/files
Get rid of the branch reference.
=> Remove 1.8.latest core reference from install.

.changes/unreleased/Fixes-20240906-102642.yaml, dbt/include/redshift/macros/relations/materialized_view/drop.sql, tests/functional/__init__.py, tests/functional/adapter/__init__.py, tests/functional/adapter/materialized_view_tests/__init__.py, tests/functional/adapter/materialized_view_tests/test_drop_cascade.py
resolves #642
We drop materialized views with a standard `DROP` instead of a `DROP ... CASCADE`. When a dbt project has materialized views that reference other materialized views, the materialized view cannot be dropped during a full refresh. This raises a database error.
Update the `DROP` statement to a `DROP ... CASCADE` statement.
=> Add cascade to drop mv

.changes/unreleased/Features-20240826-123954.yaml, dbt/adapters/redshift/connections.py, dbt/adapters/redshift/impl.py, dev-requirements.txt, tests/boundary/conftest.py, tests/boundary/test_redshift_connector.py, tests/functional/__init__.py, tests/functional/test_columns_in_relation.py
resolves #555
`dbt-redshift` references `pg_catalog` tables in its metadata queries. It should rely on Redshift's SDK or `information_schema` tables.
- Retire references to `pg_catalog` behind a behavior flag
- Move to SDK calls when possible
- Fall back on SQL calls that avoid referencing `pg_catalog`
=> Use `redshift_connector`'s `get_columns` call to get column metadata

dbt/adapters/redshift/impl.py
We added a required field to behavior flags.
Fill in the description for now. We can replace this with the url to the behavior flag on docs.getdbt.com once the docs are updated.
=> Add description to pg catalog flag

.changes/unreleased/Breaking Changes-20241016-190600.yaml, .github/workflows/integration.yml, .github/workflows/main.yml, .github/workflows/release-internal.yml, .github/workflows/release-prep.yml, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, dev-requirements.txt, docker/Dockerfile, docker/dev.Dockerfile, setup.py, tox.ini
Python 3.8 reached end of life on 10/7/2024.
Drop support for Python 3.8. Update tests to no longer run on Python 3.8.
=> Drop support for Python 3.8

.pre-commit-config.yaml
Backport #931 addition
The python version was specified in `.pre-commit-config.yml`, which was missed during the backport as this is not the case in newer versions.
=> [Backport 1.4.latest] Drop support for Python 3.8 #2

.changes/unreleased/Fixes-20241023-104556.yaml, setup.py
resolves #930
We never pinned build dependencies to final releases when creating the minor branch.
Pin `dbt-common`, `dbt-adapters`, and `dbt-core` to final releases to avoid getting pre-releases (e.g. 1.9.0b1).
=> [Bug 1.8.latest] Pin build dependencies to final releases

.changes/unreleased/Fixes-20241101-150335.yaml, dbt/adapters/redshift/connections.py, dbt/adapters/redshift/impl.py, tests/functional/test_columns_in_relation.py
resolves #914
We implemented `redshift-connector`'s `get_columns` method for column metadata generation behind a behavior flag. However, it appears there are scenarios where `get_columns` does not find an object whereas the existing custom query does find this object. This is causing failures when this new functionality is turned on. When the functionality is turned off, the user experiences a warning every run.
We have elected to remove the new approach for now as turning it on is not an option and turning it off results in a warning on which the user cannot take action. The new methods and the behavior flag have all been removed. The relevant tests have been skipped so that they may be used again once the source of the discrepancy has been resolved.
=> Remove `get_columns` implementation for column metadata generation

.github/workflows/integration.yml
`psycopg2-binary` did not publish a wheel for Python 3.9 on `macos-14`.
Test `macos-14` against Python 3.10.
=> Test `macos-14` on Python 3.10 instead of Python 3.9 due to missing `psycopg2-binary`

.github/workflows/integration.yml
Matrix strategy entries need to be arrays, even when there is only one value, but we left it as the value itself.
Wrap the single value in `[]`.
=> Fix integration test matrix

.changes/unreleased/Features-20241002-171112.yaml, dbt/adapters/redshift/impl.py, dbt/include/redshift/macros/materializations/incremental_merge.sql, tests/functional/adapter/incremental/test_incremental_microbatch.py
resolves #923
dbt-redshift needs a microbatch implementation that: 
* efficiently inserts new batches of data knowing that `compiled_code` will be filtered down by event_time
* does not require a `unique_key` configuration on the model.
We did a custom implementation of delete+insert specifically for microbatch
=> Add microbatch strategy

.changes/unreleased/Under the Hood-20241211-145132.yaml, dbt/include/redshift/macros/materializations/incremental_merge.sql
resolves #966
During the betas/rcs of dbt-core 1.9.0, the varaibles `__dbt_internal_event_time_start` and `__dbt_internal_event_time_end` were available on the model in the jinja context. However when the final of dbt-core 1.9.0 was released, dbt-core started providing a `batch` object on the model available in the jinja context. This batch object made availble all the prevous information and more, and it is the "correct" way to get the information (i.e. `__dbt_internal_event_time_end` and `__dbt_internal_event_time_start` are deprecated.
Update the microbatch incremental strategies to use `model.batch.<variable>` variables
=> Refactor to use new batch context varaibles

.changes/unreleased/Features-20241217-181340.yaml, dbt/adapters/redshift/auth_providers.py, dbt/adapters/redshift/connections.py, hatch.toml, pyproject.toml, tests/functional/test_auth_method.py, tests/unit/test_auth_method.py
resolves #898 
Add `refresh_token`-based authentication method. `refresh_token` allows for use of Iam Idc tokens that we generate adhoc for the `redshift_connector.connect` call. We had originally sought to provide a single access token and reuse it until TTL reached, but this is impossible -- tokens are only good for one use in this integration. Hence we must adhoc generate one each time and refresh tokens are an expedient and industry compliant method for doing so
Provide a refresh token endpoint and necessary information to enable this.
End to end test using the following profile which points to a test redshift cluster on an AWS account with an integrated Okta <> Iam idc <> Redshift token authentication suite.
```
class TestMyTest:
@pytest.fixture(scope="class")
def models(self): …
```
=> Add Redshift Iam Idc token authentication method with an eye towards future supported Idps 

.github/workflows/integration.yml, .github/workflows/main.yml
=> Remove artifacts workflows 1.6

.github/workflows/main.yml
Backport of #985, but using the `setup.py` based build tools instead of `pyproject.toml` build tools.
=> [Backport 1.9.latest] Combine the build and check build jobs into one job

.github/workflows/main.yml, dev-requirements.txt
Backport #984 #986 to `1.8.latest`
=> [Backport 1.8.latest] Combine build and check build jobs into one job
