dbt-labs/dbt-redshift

- setup.py
Realized this during my work on https://github.com/dbt-labs/dbt-core/pull/4133
> Use long description for PyPi

- CHANGELOG.md
- dbt/adapters/redshift/connections.py
- dbt/adapters/redshift/impl.py
- dev_requirements.txt
- tests/integration/base.py
- tests/integration/query_comments_test/test_query_comments.py
Updates to allow adapter to use new struct logger in dbt-core [#4176](https://github.com/dbt-labs/dbt-core/pull/4176)
> update for structlog AdapterLogger

- .bumpversion.cfg
- CHANGELOG.md
- dbt/adapters/redshift/__version__.py
> [Backport] Bumping version to 1.0.0 (#47)

- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/version-bump.yml
> [Backport] #122

- tests/integration/sources_test/test_sources.py
Fix test from struct logging changes
> fix integration test by resetting globals

- .github/workflows/integration.yml
- .github/workflows/main.yml
resolves #https://github.com/dbt-labs/dbt-core/issues/6203
Upgrade actions/setup-python from v2 to v4.3.0 to bring in all the updates for deprecations
Defines Python Version to use when installing dependencies
> [Backport][CT-1469] short term python version issue fix (#211)

- tox.ini
Backporting very specifically the tox changes from PR #230 .
> 1.1.latest backport of tox 4.0.0 passenv fixes

- .changes/unreleased/Under the Hood-20221208-011018.yaml
- Makefile
- tests/unit/test_context.py
- tests/unit/utils.py
- tox.ini
> Make tox.ini conform to 4.0.0 release requirements

- .github/workflows/release.yml
> fix release.yml pypi steps

- .bumpversion.cfg
> remove setup.py from version cfg

- .bumpversion.cfg
> remove setup.py from version cfg (#261)

- .changes/unreleased/Features-20230127-155317.yaml
- dbt/adapters/redshift/__init__.py
- dbt/adapters/redshift/column.py
- dbt/adapters/redshift/impl.py
- dbt/adapters/redshift/relation.py
resolves #290 
Split out the RedshiftColumn class into its own module to match the convention in other adapters
> [CTE-1941] Stand-alone Python module for RedshiftColumn

- .changie.yaml
- .github/workflows/bot-changelog.yml
> [BACKPORT] Remove PR requirement from Changelog (#280)

- .bumpversion.cfg
- .github/workflows/nightly-release.yml
- setup.py
Port https://github.com/dbt-labs/dbt-redshift/pull/326 to `main`
Fixes nightly release tests
> fix release bugs on redshift for version and workflow (#326)

- .github/scripts/integration-test-matrix.js
- .github/workflows/bot-changelog.yml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .github/workflows/version-bump.yml
- CONTRIBUTING.MD
- tox.ini
resolves #
Similar to (https://github.com/dbt-labs/dbt-core/pull/7095) and some workflow clean up
> Remove python 3.9 from main workflow

- .changes/unreleased/Features-20230301-113553.yaml
- dbt/include/redshift/macros/adapters.sql
- dev-requirements.txt
- tests/functional/adapter/test_constraints.py
resolves #340 
Support contracts for view materializations.
> support contracts on models materialized as view #584

- .github/workflows/integration.yml
resolves #380 
Make dependabot PRs easier to test.
> Adjust workflow.

- dev-requirements.txt
- tests/functional/adapter/test_constraints.py
resolves https://github.com/dbt-labs/dbt-core/issues/7154
Adds (and reorganizes) tests.
> add test for enforcing contracts on incremental materializations

- .changes/1.5.0/Under the Hood-20230223-110314.yaml
- .changes/unreleased/Under the Hood-20230223-110314.yaml
- dbt/include/redshift/macros/adapters.sql
- dev-requirements.txt
resolves #382
contract config is now an object in `dbt-core` https://github.com/dbt-labs/dbt-core/pull/7222
> update to retrieve contract enforced from dict

- .changes/unreleased/Fixes-20230411-143706.yaml
- dev-requirements.txt
> Repair accidental change to dev-requirements

- .github/workflows/integration.yml
- .github/workflows/main.yml
resolves #250 
Fixes last remaining instances of set-output.
> updating set-output

- .changes/unreleased/Fixes-20230520-043039.yaml
- dbt/adapters/redshift/connections.py
- tests/functional/adapter/test_autocommit.py
> [backport] Add autocommit feature to let dbt users run certain db commands in macros

- .changes/0.0.0.md
- CHANGELOG.md
resolves #
adding link to 1.5.latest changelog
> adding link to 1.5 release notes

- .github/workflows/nightly-release.yml
resolves #
pointer to test nightly releases was changed, reverting back to point to a `.latest` branch to fix tests nightly run.
> re-pointing reelease branch env for nightly releases to a .latest branch

- .changes/unreleased/Breaking Changes-20230614-144743.yaml
- setup.py
> increase minimum required version of `redshift_connector` driver

- .changes/unreleased/Breaking Changes-20230530-165542.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- CONTRIBUTING.md
- dev-requirements.txt
- setup.py
- tox.ini
- drop support for py37 (#474)
resolves #
> backport 474 to 1.5.latest

- .github/workflows/nightly-release.yml
Fix the release branch from the py37 decom backport.
> fix release branch from recent backport

- .changes/unreleased/Breaking Changes-20230530-165542.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- .github/workflows/nightly-release.yml
- CONTRIBUTING.MD
- setup.py
- tox.ini
Dropping support for py37 backport (#474)
> [Backport 1.3.latest] Dropping support for py37

- .changes/unreleased/Breaking Changes-20230530-165542.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- CONTRIBUTING.MD
- setup.py
- tox.ini
Dropping support for py37 backport (#474)
> [Backport 1.1.latest] Dropping support for py37

- .changes/unreleased/Breaking Changes-20230530-165542.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- CONTRIBUTING.MD
- setup.py
- tox.ini
Dropping support for py37 backport (#474)
> [Backport 1.0.latest] Dropping support for py37

- .changes/unreleased/Fixes-20230706-123329.yaml
- dbt/adapters/redshift/connections.py
- setup.py
resolves https://github.com/dbt-labs/dbt-redshift/issues/518
Casts the port as an integer
> cast port as integer

- .changes/unreleased/Fixes-20230706-123329.yaml
- dbt/adapters/redshift/connections.py
- setup.py
* cast port as integer
* remove pin to exclude rs_connector 2.0.912
resolves #
> [BACKPORT] cast port as integer (#523)

- .changes/unreleased/Features-20230407-104723.yaml
Updating the changelog entry of https://github.com/dbt-labs/dbt-redshift/pull/428 per  @dbeatty10's suggestion in https://github.com/dbt-labs/dbt-redshift/pull/428#issuecomment-1634232202
> update changelog - this fix does not resolve 217 and 17

- .changes/unreleased/Fixes-20230713-105351.yaml
- setup.py
> [BACKPORT] manual backport of pr 530

- .github/workflows/integration.yml
- dev-requirements.txt
- tox.ini
> [Backport 1.4.latest] Add Datadog Env Vars

- .changes/unreleased/Under the Hood-20230914-135547.yaml
> Update Under the Hood-20230914-135547.yaml

- .github/workflows/docs-issues.yml
resolves #https://github.com/dbt-labs/actions/issues/111
Overlooking docs changes related to `dbt-core` and adapters changes
Automate the creation of docs issues by adding the `user docs` a label to merged PRs
> add docs-issue workflow to dbt-redshift

- .changes/unreleased/Dependencies-20230912-120620.yaml
- setup.py
- Update redshift-connector requirement from 2.0.913 to 2.0.915 (#601)
resolves #
> backport 601 to 1.6.latest

- .changes/unreleased/Dependencies-20230912-120620.yaml
- setup.py
- Update redshift-connector requirement from 2.0.913 to 2.0.915 (#601)
resolves #
> backport 601 to 1.7.latest

- .changes/unreleased/Dependencies-20231130-044332.yaml
- setup.py
- tests/functional/adapter/test_basic.py
- tests/unit/test_redshift_adapter.py
> Backport #674 to 1.6.latest

- .changes/unreleased/Under the Hood-20231214-131521.yaml
- .github/workflows/main.yml
resolves #
code_quality failures appearing in 1.2.latest branches which are at eol
remove check
> remove code_quality check from main.yml

- dev-requirements.txt
- tests/functional/adapter/test_query_comment.py
> fix redshift dev reqs

- .changes/unreleased/Dependencies-20240118-095025.yaml
- setup.py
- upgrade redshift driver to 2.0.918
- upgrade redshift driver to 2.0.918
resolves #
> loosen redshift-connector dependency <=2.0.918, >=2.0.913

- .changes/unreleased/Dependencies-20240319-101832.yaml
- dev-requirements.txt
resolves #734 
A change in ddtrace or a upper dependency around helpconfig seems to be causing failures in adapters. setting bounds to be in the 2.3.x range seems to get us passing.
> Test ddtrace dependency range

- .changes/unreleased/Dependencies-20240319-101832.yaml
- dev-requirements.txt
> [Backport 1.3.latest] Test ddtrace dependency range (#733)

- .changes/unreleased/Dependencies-20240319-101832.yaml
- dev-requirements.txt
> [Backport 1.2.latest] Test ddtrace dependency range (#733)

- .changes/unreleased/Under the Hood-20240410-182912.yaml
- .github/dependabot.yml
We have inconsistent and under-configured dependabot config files.
Consistify them.
> Update dependabot config to cover GHA

- .github/workflows/integration.yml
> Make space for both user and role in testing, add role environment variables

- dev-requirements.txt
> Update dev-requirements.txt to point to 1.8.latest

- .github/workflows/integration.yml
> [Backport 1.6.latest] Fix macos runner typo (#820)

- .github/workflows/main.yml
> [Backport 1.2.latest] Swap the order of the sdist and wheel checks (#866)

- .github/workflows/main.yml
> [Backport 1.1.latest] Swap the order of the sdist and wheel checks (#866)

- .github/workflows/main.yml
> [Backport 1.0.latest] Swap the order of the sdist and wheel checks (#866)

- .changes/unreleased/Breaking Changes-20241016-190600.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.5.latest] Drop support for Python 3.8

- .changes/unreleased/Breaking Changes-20241016-190600.yaml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.6.latest] Drop support for Python 3.8

- .changes/unreleased/Breaking Changes-20241016-190600.yaml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.7.latest] Drop support for Python 3.8

- .changes/unreleased/Breaking Changes-20241016-190600.yaml
- .github/workflows/integration.yml
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.8.latest] Drop support for  Python 3.8

- .changes/unreleased/Breaking Changes-20241016-190600.yaml
- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
- Makefile
- setup.py
- tox.ini
> [Backport 1.4.latest] Drop support for Python 3.8

- .github/workflows/integration.yml
- .github/workflows/main.yml
> move github runner from macos-12 to macos-14 (#941, #942, #943)

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
resolves #
1.4 tests will fail on macos until we fix this.
Go to a version with a psycopg2 binary.
> Fix macos14 tests on 1.5

- .github/scripts/integration-test-matrix.js
- .github/workflows/main.yml
resolves #
1.4 tests will fail on macos until we fix this.
Go to a version with a psycopg2 binary.
> Update the macos14 python version

- setup.py
> Update setup.py to not use dbt-core pre-release

- .github/workflows/release-internal.yml
> Update release-internal.yml to use hatch

- .github/workflows/integration.yml
- .github/workflows/main.yml
> Remove the artifacts related workflow steps

- .github/workflows/main.yml
> [Backport 1.7.latest] Combine build and build check jobs into one job

- .github/workflows/main.yml
> [Backport 1.6.latest] Combine the build and check build jobs into one job

- .github/workflows/main.yml
> [Backport 1.5.latest] Combine the build and check build jobs into one job

- .github/workflows/main.yml
> [Backport 1.4.latest] Combine the build and check build jobs into one job
